### ISSUE TITLE
blue_thermal_printer package is missing

### ISSUE THREAD

**Issue by kvvaradha** [imesh562/sales-rep-management-app-flutter#1]
hello dude, 

This is awesome work. but i cant see the app without this BlueThermalPrinterPlugin.

So change the blue_thermal_printer: ^1.2.0 and it will work.

**Comment by kvvaradha** [comment]
what is the login details to check the app. ?

**Comment by imesh562** [comment]
updated the plugin there shouldn't be a problem now.
